Working arch kde install scripts

diff --git a/Scripts/common/install_favorites b/Scripts/common/install_favorites
--- a/Scripts/common/install_favorites
+++ b/Scripts/common/install_favorites
@@ -1,24 +1,20 @@
 #!/bin/bash
 
-currentDE=$(./get_desktop_env)
+currentPackageManager="$1"
+currentDE="$2"
 
-current_distro=$(./get_distro)
-
-# echo $current_distro
-case $current_distro in
-    fedora) currentPackageManager="dnf";;
-    arch) currentPackageManager="pacman";;
-    ubuntu) currentPackageManager="apt";;
-    manjaro) currentPackageManager="pacman";;
-    "garuda linux") currentPackageManager="pacman";;
-esac
-
-# echo $currentPackageManager
-
-if [[ $currentDE == '-h' || $currentDE == '--help' ]]
+if [[ $1 == '-h' || $1 == '--help' ]]
 then
-    echo "Usage: install_favorites DESKTOPENV(kde, qtile) DISTRO(fedora, arch)"
+    echo "Usage: install_favorites DESKTOPENV(kde, qtile) DISTRO(fedora, arch)" && exit;
 fi
+
+echo
+tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
+tput setaf 2;echo "............  Installing Favorite Applications  ...............";tput sgr0;
+tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
+
+
+sudo true;
 
 packageListqtile=(
     ## notification daemon, rofi and alacritty
@@ -85,10 +81,6 @@ packageListqtile=(
     python3-pip
     python-pip
     axel
-)
-
-yayListqtile=(
-    # Fonts
     ttf-mononoki-git
 )
 
@@ -121,6 +113,7 @@ packageListkde=(
     python-pip
     
     axel
+    latte-dock-git
 )
 
 yay_install() {
@@ -143,48 +136,89 @@ installPackages(){
 }
 
 installYayPackages(){
-    req_list=yaylist$x[@]
+    count=0
+    x=$currentDE
+    req_list=packageList$x[@]
     for name in "${!req_list}" ; do
         count=$[count+1]
-        tput setaf 3;echo "Installing package nr.  "$count " " $name;tput sgr0;
-        yay_install $name
+        tput setaf 3;echo "Installing package #.  "$count " " $name;tput sgr0;
+        install_package $name
     done
 }
 
 install_yay(){
-    sudo pacman -Syyu --noconfirm
-    sudo pacman -S git --noconfirm
-    mkdir -p ~/Downloads
-    cd ~/Downloads || exit
-    git clone https://aur.archlinux.org/yay.git
-    cd yay
-    makepkg -si
+    if ! type "yay" >> /dev/null 2>&1; then
+        echo "Installing Yay"
+        sudo pacman -Syyu --noconfirm
+        sudo pacman -S git --noconfirm
+        mkdir -p ~/Downloads
+        cd ~/Downloads || exit
+        git clone https://aur.archlinux.org/yay.git
+        cd yay
+        makepkg -si
+    fi
 }
+
+
+
+### Arch specific stuff ###
+ua-drop-caches(){
+    sudo paccache -rk3;
+    yay -Sc --aur --noconfirm
+}
+ua-update-all(){
+    export TMPFILE="$(mktemp)";
+    sudo true;
+    rate-arch-mirrors --max-delay=21600 | tee -a $TMPFILE || exit \
+    && sudo mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist-backup \
+    && sudo mv $TMPFILE /etc/pacman.d/mirrorlist \
+    && ua-drop-caches \
+    && yay -Syyu --noconfirm
+}
+### end ###
+
 
 case $currentPackageManager in
     "dnf")
         sudo dnf update -y
         currentPMSyntax="dnf install -y"
+        installPackages
     ;;
     
     "pacman")
-        sudo pacman --noconfirm -Syyu
-        install_yay
-        yay_install
+        install_yay || (echo "Yay cannot be installed, hence aborting" && exit);
+        yay --needed --noconfirm -S rate-arch-mirrors || (echo "Rate arch mirrors cannot be installed, hence aborting" && exit);
+        ua-drop-caches
+        ua-update-all
         currentPMSyntax="pacman --needed --noconfirm -S "
+        installYayPackages
     ;;
+    
+    "apt")
+        sudo apt update -y
+        currentPMSyntax="apt install -y"
+        installPackages
+    ;;
+    
+    *)
+    echo "Wrong package manager. Please check install_favorites" && exit;;
+    
+    
 esac
-installPackages
+
+# Install pywal (wallpaper)
 sudo pip3 install pywal
+
 echo
 tput setaf 2;echo "Installation Successfull!";tput sgr0;
 tput setaf 5;echo "Reboot now!!!";tput sgr0;
 
 
 tput setaf 2;echo "Instaling Other Apps...";tput sgr0;
-./install_google_chrome
-./install_visual_studio_code
-./install_brave
+
+./install_google_chrome $1
+./install_visual_studio_code $1
+./install_brave $1
 
 
 
diff --git a/Scripts/common/make_executables b/Scripts/common/make_executables
--- a/Scripts/common/make_executables
+++ b/Scripts/common/make_executables
@@ -1,13 +1,19 @@
 #!/bin/bash
 
-chmod +x *
 
-cd extras/ || exit
+echo
+tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
+tput setaf 2;echo ".............  Making all scripts executable  .................";tput sgr0;
+tput setaf 3;echo "---------------------------------------------------------------";tput sgr0;
 
-chmod +x *
+chmod +x utils/* || echo "cannot modify"
+
+chmod +x ./*
 
 mkdir -vp ~/.local/bin/
 
-mkdir -v ~/.config/
+mkdir -vp ~/.config/
 
-mkdir -v ~/.cache/
+mkdir -vp ~/.cache/
+
+# Tested works fine
